### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by lukasschneider911** [madmachinations/home-assistant-alexa-shopping-list#26]
Hi!
I installed the "Alexa Shopping List Sync" as an Add-on in my Home Assistant OS setup. I also installed the "Advanced SSH & Web Terminal" Add-on to execute the Python client-script to configure the server. I managed to get it authenticated with "amazon.de" and was initially able to display my shopping list items using the "list" command.

Since the "Alexa Shopping List" integration failed to synchronize, I went back to the client to verify the authentication but receive this error message ever since:
```
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 1287, in close_connection
    await self.transfer_data_task
  File "/usr/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 953, in transfer_data
    message = await self.read_message()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 1023, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 1098, in read_data_frame
    frame = await self.read_frame(max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 1155, in read_frame
    frame = await Frame.read(
            ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/websockets/legacy/framing.py", line 70, in read
    data = await reader(2)
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/streams.py", line 752, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/lib/python3.12/asyncio/streams.py", line 545, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/homeassistant/client/client.py", line 288, in <module>
    asyncio.run(client.run_console())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/homeassistant/client/client.py", line 274, in run_console
    keep_running = await self._handle_commands(command, arguments)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homeassistant/client/client.py", line 236, in _handle_commands
    await self._cmd_get_shopping_list()
  File "/homeassistant/client/client.py", line 188, in _cmd_get_shopping_list
    response = await self._send_command("get_list")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homeassistant/client/client.py", line 39, in _send_command
    response = await websocket.recv()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 562, in recv
    await self.ensure_open()
  File "/usr/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 938, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1011 (internal error) keepalive ping timeout; no close frame received
```
In the Add-on log the error looks like this:
```
connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/websockets/legacy/server.py", line 245, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3.12/site-packages/websockets/legacy/server.py", line 1188, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/server/server.py", line 250, in _process_command
    async for message in websocket:
  File "/usr/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 494, in __aiter__
    yield await self.recv()
          ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 564, in recv
    await self.ensure_open()
  File "/usr/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 940, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: received 1011 (internal error) keepalive ping timeout; then sent 1011 (internal error) keepalive ping timeout
```
It looks like the server is running into a timeout.

Do you have an idea, what could be causing this?

Cheers,
Lukas

**Comment by madmachinations** [comment]
Is this running on a raspberry pi, by any chance?

**Comment by lukasschneider911** [comment]
It is running as VM under Synology Virtual Machine Manager.
Am 25. Okt. 2024, 15:51 +0200 schrieb Madmachinations ***@***.***>:

**Comment by madmachinations** [comment]
> It is running as VM under Synology Virtual Machine Manager. Am 25. Okt. 2024, 15:51 +0200 schrieb Madmachinations ***@***.***>:
> […](#)
> Is this running on a raspberry pi, by any chance? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

What is the spec?

**Comment by lukasschneider911** [comment]
The VM has 8 Cores and 8 GB RAM.

**Comment by madmachinations** [comment]
Hello, please try again with the latest version.

A number of changes have been made, not all of them deployed. But a fix for the authentication issues should be out in the latest version.

It is important you delete any running version of the server you might currently have, and scrub out any of it's persisted cached files to ensure a clean slate. Then install the latest version from scratch.

You will also need to download the latest client script from this repository.

If you are using the server as a HASS Add-on, you should also delete the custom repository you added to install the add on, as this has now moved to here:

https://github.com/madmachinations/home-assistant-alexa-shopping-list/releases

So you will need to setup the new repository and install the new server version from there.

As part of the changes I have migrated the build process over to github actions and I have added some extra provisions which made it irritating to deploy changes before. So moving ahead:

- There will be a new release on the releases page for each version, where you can always access the historical project files and client for specific versions. These are being created automatically when a new build is put out
- When a new version is released, the HASS add-on repository is being automatically updated also. Which should flag new server versions to everyone's HASS installations and prompt you to update.


In this case of this issue specifically @lukasschneider911, you should not be using the client on your hass device. You should be configuring it as described in the documentation. The client runs on the computer you're sat on. The server runs on the HASS device.

**Comment by madmachinations** [comment]
This fix should now be deployed in the latest version which uses the new authenticator to get everything logged in.

Please clear out your existing installation, delete all containers and old client versions. And go through the documentation on the wiki for installing the new version:

https://github.com/madmachinations/home-assistant-alexa-shopping-list/wiki/Installation

I will close this issue, if you have problems with the authenticator please post about them in #39
