### ISSUE TITLE
Docker Container Support

### ISSUE THREAD

**Issue by bachoo786** [madmachinations/home-assistant-alexa-shopping-list#30]
Hi there

I have tried to run the docker image as a container and it seems to be working. However, as you have mentioned, I won''t be seeing any logs until I connect the container/server with the files from your git. 

What I am trying to understand is that after downloading the files from your git, how would I run it using the container/server that I have? and would I need some sort of a crontab command or a systemd service file to keep on running it using my container/server?

If you could please help clarify? thank you.

**Comment by madmachinations** [comment]
Hello,

The documentation for the configuration step is here:

https://github.com/madmachinations/home-assistant-alexa-shopping-list?tab=readme-ov-file#step-2---configure-the-server

Assuming you have setup the server/container on a HA machine somewhere on your network, you would download the files in this repository to your laptop/desktop - a different computer on your network. You could run it on the same box, but how easy that is depends on whether it's a HASS box or a normal server running HA somehow.

Once downloaded, the client script in this git repository requires you specify the IP address of the computer where you are running the server jazz.

So sat on your laptop or whatever, if your HA box had the IP 192.168.0.100 on your network, you would run something like `python client.py 192.168.0.100`

As such, the client then knows to expect it can talk to the server on that specific IP address.

If no IP is specified, it will assume the server is running on the same machine and try to contact it on a local address (127.0.0.1).

**Comment by bachoo786** [comment]
Thanks for the reply.

I am running in a bridge network and my ip address is : 172.18.0.14

so when I ran python client.py 172.18.0.14

it worked and I put in my base url which is amazon.co.uk and my credentials but then I got this error:

```
Traceback (most recent call last):
  File "client.py", line 288, in <module>
    asyncio.run(client.run_console())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "client.py", line 259, in run_console
    await self._check_server()
  File "client.py", line 84, in _check_server
    await self._setup_server_authentication()
  File "client.py", line 131, in _setup_server_authentication
    response = await self._send_command("login", email=email, password=password)
  File "client.py", line 39, in _send_command
    response = await websocket.recv()
  File "/home/bachoo786/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/home/bachoo786/.local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 948, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: received 1011 (internal error); then sent 1011 (internal error)

```

**Comment by bachoo786** [comment]
ok I suppose the ip address was an issue. I managed to sort everything I am just at the custom component and I have provided the ip and the host but I keep getting the loading round circle. here are the logs:

```
2024-11-25 16:49:02.431 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Alexa Shopping List for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 133, in async_setup_entry
    return await hass.data[DATA_COMPONENT].async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 197, in async_setup_entry
    return await self._platforms[key].async_setup_entry(config_entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 332, in async_setup_entry
    return await self._async_setup_platform(async_create_setup_awaitable)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 373, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 648, in async_add_entities
    await add_func(coros, entities, timeout)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 557, in _async_add_and_update_entities
    results = await asyncio.gather(*tasks, return_exceptions=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 728, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1302, in async_device_update
    await self.async_update()
  File "/config/custom_components/alexa_shopping_list/sensor.py", line 42, in async_update
    updated = await self.alexa.sync(_LOGGER)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_shopping_list/asl.py", line 219, in sync
    await self._add_item(item)
  File "/config/custom_components/alexa_shopping_list/asl.py", line 122, in _add_item
    response = await self._send_command("add_item", item=item)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_shopping_list/asl.py", line 35, in _send_command
    response = await websocket.recv()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 546, in recv
    await asyncio.wait(
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 464, in wait
    return await _wait(fs, timeout, return_when, loop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 550, in _wait
    await waiter
asyncio.exceptions.CancelledError

```

**Comment by bachoo786** [comment]
ok so i think i sorted it.. I have got the list see screenshot:

![image](https://github.com/user-attachments/assets/adc8b58d-39ad-4bbb-81c9-cd5a1bf3e335)

the issue now is that whatever I add to Alexa shopping list doesn't get synced in with HA. This Alexa Shopping List component says Unknown status. Is it due to the sync time? i.e. 60 minutes?

**Comment by bachoo786** [comment]
says authenticated but when i check the list says its not authenticated:

```
bachoo786@bachoo786:/srv/docker/homeassistant/home-assistant-alexa-shopping-list/client$ python3 client.py 127.0.0.1
Alexa Shopping List Sync Client Console.

Attempting to connect to ws://127.0.0.1:4000
Connected successfully

Checking config
Config is valid

Checking authentication
Server is authenticated

Type 'help' for commands.

> list
ERROR: Not authenticated
```

**Comment by bachoo786** [comment]
here is more for you: @madmachinations seems like on the amazon.co.uk page they have removed "remember me" class/option:


```
2024-11-25T17:35:39.162840859Z     await self.ensure_open(),
2024-11-25T17:35:39.162850787Z   File "/usr/lib/python3.12/site-packages/websockets/legacy/protocol.py", line 931, in ensure_open,
2024-11-25T17:35:39.162864947Z     raise self.connection_closed_exc(),
2024-11-25T17:35:39.162875859Z websockets.exceptions.ConnectionClosedError: no close frame received or sent,
2024-11-25T17:50:10.723801402Z connection handler failed,
2024-11-25T17:50:10.723883725Z Traceback (most recent call last):,
2024-11-25T17:50:10.723901703Z   File "/usr/lib/python3.12/site-packages/websockets/legacy/server.py", line 245, in handler,
2024-11-25T17:50:10.723918208Z     await self.ws_handler(self),
2024-11-25T17:50:10.723933599Z   File "/usr/lib/python3.12/site-packages/websockets/legacy/server.py", line 1188, in _ws_handler,
2024-11-25T17:50:10.723950437Z     return await cast(,
2024-11-25T17:50:10.723965941Z            ^^^^^^^^^^^,
2024-11-25T17:50:10.723981134Z   File "/server/server.py", line 271, in _process_command,
2024-11-25T17:50:10.723996875Z     results = await _route_command(command, arguments),
2024-11-25T17:50:10.724012373Z               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^,
2024-11-25T17:50:10.724027832Z   File "/server/server.py", line 239, in _route_command,
2024-11-25T17:50:10.724043738Z     return await _cmd_login(arguments),
2024-11-25T17:50:10.724059108Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^,
2024-11-25T17:50:10.724074354Z   File "/server/server.py", line 147, in _cmd_login,
2024-11-25T17:50:10.724090119Z     instance.login(args['email'], args['password']),
2024-11-25T17:50:10.724105716Z   File "/server/alexa.py", line 196, in login,
2024-11-25T17:50:10.724121508Z     self._handle_login(),
2024-11-25T17:50:10.724136832Z   File "/server/alexa.py", line 184, in _handle_login,
2024-11-25T17:50:10.724152507Z     self._handle_login_password_page(),
2024-11-25T17:50:10.724167899Z   File "/server/alexa.py", line 159, in _handle_login_password_page,
2024-11-25T17:50:10.724183945Z     self.driver.find_element(By.NAME, 'rememberMe').click(),
2024-11-25T17:50:10.724199808Z     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^,
2024-11-25T17:50:10.724250788Z   File "/usr/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 748, in find_element,
2024-11-25T17:50:10.724267739Z     return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"],
2024-11-25T17:50:10.724283176Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^,
2024-11-25T17:50:10.724297726Z   File "/usr/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute,
2024-11-25T17:50:10.724312500Z     self.error_handler.check_response(response),
2024-11-25T17:50:10.724326776Z   File "/usr/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response,
2024-11-25T17:50:10.724398257Z     raise exception_class(message, screen, stacktrace),
2024-11-25T17:50:10.724411805Z selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="rememberMe"]"},
2024-11-25T17:50:10.724426203Z   (Session info: chrome=129.0.6668.70); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception,
2024-11-25T17:50:10.724439812Z ,
2024-11-25T17:52:59.578668979Z connection handler failed,
2024-11-25T17:52:59.578739928Z Traceback (most recent call last):,
2024-11-25T17:52:59.578752303Z   File "/usr/lib/python3.12/site-packages/websockets/legacy/server.py", line 245, in handler,
2024-11-25T17:52:59.578763760Z     await self.ws_handler(self),
2024-11-25T17:52:59.578774991Z   File "/usr/lib/python3.12/site-packages/websockets/legacy/server.py", line 1188, in _ws_handler,
2024-11-25T17:52:59.578786076Z     return await cast(,
2024-11-25T17:52:59.578796456Z            ^^^^^^^^^^^,
2024-11-25T17:52:59.578806821Z   File "/server/server.py", line 271, in _process_command,
2024-11-25T17:52:59.578817631Z     results = await _route_command(command, arguments),
2024-11-25T17:52:59.578828068Z               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^,
2024-11-25T17:52:59.578838471Z   File "/server/server.py", line 239, in _route_command,
2024-11-25T17:52:59.578849190Z     return await _cmd_login(arguments),
2024-11-25T17:52:59.578859844Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^,
2024-11-25T17:52:59.578870229Z   File "/server/server.py", line 147, in _cmd_login,
2024-11-25T17:52:59.578880862Z     instance.login(args['email'], args['password']),
2024-11-25T17:52:59.578891229Z   File "/server/alexa.py", line 196, in login,
2024-11-25T17:52:59.578901737Z     self._handle_login(),
2024-11-25T17:52:59.578911930Z   File "/server/alexa.py", line 184, in _handle_login,
2024-11-25T17:52:59.578922470Z     self._handle_login_password_page(),
2024-11-25T17:52:59.578933107Z   File "/server/alexa.py", line 159, in _handle_login_password_page,
2024-11-25T17:52:59.578970616Z     self.driver.find_element(By.NAME, 'rememberMe').click(),
2024-11-25T17:52:59.578981556Z     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^,
2024-11-25T17:52:59.578991463Z   File "/usr/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 748, in find_element,
2024-11-25T17:52:59.579001884Z     return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"],
2024-11-25T17:52:59.579012461Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^,
2024-11-25T17:52:59.579022428Z   File "/usr/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute,
2024-11-25T17:52:59.579032645Z     self.error_handler.check_response(response),
2024-11-25T17:52:59.579042404Z   File "/usr/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response,
2024-11-25T17:52:59.579052956Z     raise exception_class(message, screen, stacktrace),
2024-11-25T17:52:59.579063041Z selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="rememberMe"]"},
2024-11-25T17:52:59.579074349Z   (Session info: chrome=129.0.6668.70); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception,
2024-11-25T17:52:59.579085234Z ,
2024-11-25T17:55:39.048482829Z connection handler failed,
2024-11-25T17:55:39.048552577Z Traceback (most recent call last):,
2024-11-25T17:55:39.048564253Z   File "/usr/lib/python3.12/site-packages/websockets/legacy/server.py", line 245, in handler,
2024-11-25T17:55:39.048575876Z     await self.ws_handler(self),
2024-11-25T17:55:39.048585837Z   File "/usr/lib/python3.12/site-packages/websockets/legacy/server.py", line 1188, in _ws_handler,
2024-11-25T17:55:39.048596180Z     return await cast(,
2024-11-25T17:55:39.048605869Z            ^^^^^^^^^^^,
2024-11-25T17:55:39.048615603Z   File "/server/server.py", line 271, in _process_command,
2024-11-25T17:55:39.048626096Z     results = await _route_command(command, arguments),
2024-11-25T17:55:39.048636131Z               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^,
2024-11-25T17:55:39.048645983Z   File "/server/server.py", line 239, in _route_command,
2024-11-25T17:55:39.048656279Z     return await _cmd_login(arguments),
2024-11-25T17:55:39.048666155Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^,
2024-11-25T17:55:39.048675852Z   File "/server/server.py", line 147, in _cmd_login,
2024-11-25T17:55:39.048685861Z     instance.login(args['email'], args['password']),
2024-11-25T17:55:39.048695696Z   File "/server/alexa.py", line 196, in login,
2024-11-25T17:55:39.048705746Z     self._handle_login(),
2024-11-25T17:55:39.048715599Z   File "/server/alexa.py", line 184, in _handle_login,
2024-11-25T17:55:39.048757576Z     self._handle_login_password_page(),
2024-11-25T17:55:39.048768137Z   File "/server/alexa.py", line 159, in _handle_login_password_page,
2024-11-25T17:55:39.048777888Z     self.driver.find_element(By.NAME, 'rememberMe').click(),
2024-11-25T17:55:39.048787191Z     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^,
2024-11-25T17:55:39.048796390Z   File "/usr/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 748, in find_element,
2024-11-25T17:55:39.048806212Z     return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"],
2024-11-25T17:55:39.048815988Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^,
2024-11-25T17:55:39.048825271Z   File "/usr/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute,
2024-11-25T17:55:39.048834900Z     self.error_handler.check_response(response),
2024-11-25T17:55:39.048844199Z   File "/usr/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response,
2024-11-25T17:55:39.048853877Z     raise exception_class(message, screen, stacktrace),
2024-11-25T17:55:39.048863224Z selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="rememberMe"]"},
2024-11-25T17:55:39.048873821Z   (Session info: chrome=129.0.6668.70); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception,
2024-11-25T17:55:39.048883753Z ,
```
